---
train:

    params:
        batch_size: 64
        epoch: 60
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "/home/user/wyl/DVGaze-main/Code/eth"
        folder: eth
        model_name: trans
        step: 5

    data:
        image: "/data/wyl_data/ETH-Gaze/Image/traincrop"
        label_cam1: "/home/user/wyl/DVGaze-main/Label/ETH/cam2.train"
        label_cam2: "/home/user/wyl/DVGaze-main/Label/ETH/cam7.train"
        header: True
        cams: 
            params: "/home/user/wyl/DVGaze-main/Code/eth/readcam"
        name: eth
        isFolder: False

    pretrain:
        enable: False
        path: PLACEHOLDER
        device: PLACEHOLDER

    device: 0 
    reader: reader

# dropout = 0
# dim_feed = 512
