---
train:

    params:
        batch_size: 64
        epoch: 30
        lr: 0.001
        decay: 0.5
        decay_step: 40
        warmup: 5

    save:
        metapath: "/home/user/wyl/DVGaze-main/Code/eth"
        folder: eve
        model_name: trans
        step: 5

    data:
        image: "/data/wyl_data/EVE/Image"
        label_cam1: "/home/user/wyl/DVGaze-main/Label/EVE_origin/train/webcam_r.train"
        label_cam2: "/home/user/wyl/DVGaze-main/Label/EVE_origin/train/webcam_l.train"
        header: False
        name: eve
        isFolder: False

    pretrain:
        enable: False
        path: PLACEHOLDER
        device: PLACEHOLDER

    device: 0
    reader: reader_eve

# dropout = 0
# dim_feed = 512
